---
- hosts: all
  # sudo: True
  become: True
  vars:
  - oah_command: install
  - path_to_home: "/home/{{ vagrant_user }}"
  - clone_path: "{{ path_to_home }}/kobman_install.sh" 

  vars_files:
    - ../oah-config.yml

  pre_tasks:
    - name: "printing debug msg"
      debug:
        msg: In pre_tasks
    - name: Printing value of vagrant_user
      debug:
        msg: "Value of vagrant user: {{ vagrant_user }}; path to home: {{ path_to_home }}; clone path: {{ clone_path }}"
    # Will need the shell provision to install python-minimal first
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (sudo apt -y update && apt install -y python-minimal)
    - include: tasks/init-debian.yml
      when: ansible_os_family == 'Debian'
  roles:
    # Essential roles.
    - oah.kobman
    - oah.vscode
    - oah.oah
    # - oah.desktop
    # - oah.atom

  tasks:


    # Conditionally-installed roles.

    # Roles for security and stability on production.
